# version: '3'
# services:
#   app:
#     build:
#       context: .
#     shm_size: '2gb'
#     network_mode: host
#     volumes:
#       - ./track_data.json:/app/track_data.json  # Mount the output file
#     environment:
#       - DISPLAY=:0  # Required for running Selenium with Chrome driver
version: '3'
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: web-scrape-selenium-hub-1
    ports:
      - "4444:4444"
    networks:
      - web-scrape-network

  chrome:
    image: selenium/node-chrome:3.141.59
    container_name: web-scrape-chrome-1
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - web-scrape-network

  web-scrape-app:
    build: .
    container_name: web-scrape-web-scrape-app-1
    depends_on:
      - selenium-hub
    networks:
      - web-scrape-network
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  web-scrape-network:   # Use the correct network name here
    driver: bridge
